title: "Базовый Сценарий"
description: "Сайт посвящен рассмотрению базовых (а изредка - экстремальных) сценариев развития макроэкономических процессов в России и мире."
lang: ru-RU
theme: jekyll-theme-tactile
